export const reportBasePath = (config) => config.basePath || "/reports";
export const reportCookieName = (config) => `${config.secure ? "__Host-" : ""}${config.basePath === "/personal" ? "personal-briefs" : "briefs"}`;
export const reportLink = (config, suffix = "") => `${config.origin}${reportBasePath(config)}${suffix}`;

export function mountedTarget(target, config) {
  return target.replace(/^\/reports(?=\/|\?|#|$)/, reportBasePath(config));
}

// Rewrite only navigation generated by the application. Uploaded HTML bypasses
// this function so its original content and hash remain intact.
export function mountedPage(html, config) {
  if (reportBasePath(config) === "/reports") return html;
  return html.replace(/\b(href|action|formaction|src)=(["'])\/reports(?=[/?#"'])/g, `$1=$2${reportBasePath(config)}`)
    .replace(/\bhref=(["'])\/\1/g, `href="${reportBasePath(config)}"`);
}
