import { layout, hero, esc, hidden, profile, formButton } from "../portal/views.mjs";
import { readerShellStyles } from "./reader.mjs";
import { reportOverview, progressOverview } from "./progress-views.mjs";
export function page(title, content, role = "guest") {
  const nav = role === "admin" ? '<a href="/reports">보고서 목록</a><a href="/reports/progress">진행 관리</a><a href="/reports/upload">HTML 업로드</a><a href="/reports/admin">구독 승인</a>' : role === "publisher" ? '<a href="/reports/upload">HTML 업로드</a>' : '<a href="/reports">보고서 목록</a><a href="/reports/progress">진행 현황</a><a href="/reports/account">구독 설정</a>';
  return layout(title, content, role, nav).replace('action="/members/logout"', 'action="/reports/logout"').replace("</head>", "<style>.topbar nav{flex-wrap:wrap;min-width:0}</style></head>");
}
export function login(type, configured, channelMode = false, personal = false) {
  const heading = hero('DAILY <span>ARCHIVE.</span>', personal ? "개발·AI·IT 공모전과 채용, 미국 주식·ETF를 모아 보는 개인 보고서입니다." : "겜마루의 외부 후원·운영자금·유용한 정보를 모아 둔 보고서 보관함입니다.");
  if (type === "member" && personal) return page("개인 보고서 로그인", `${heading}<div class="panel narrow"><h2>나만 보는 데일리 브리핑</h2><p>등록된 소유자의 Discord 계정으로 로그인하세요. 새 보고서의 요약과 링크는 본인 DM으로 받습니다.</p>${configured ? '<a class="button" href="/reports/auth/discord">Discord로 로그인 →</a>' : '<p class="notice">로그인 연결을 준비 중입니다.</p>'}</div>`);
  if (type === "member") return page("보고서 로그인", `${heading}<div class="panel narrow"><h2>구독자 전용 보고서</h2><p>처음 로그인하면 Discord 이름으로 구독 신청이 접수됩니다. ${channelMode ? "관리자 승인 후 보고서를 열람할 수 있습니다. 새 보고서의 요약과 링크는 Discord 서버 채널에 게시됩니다." : "관리자 승인 후 보고서를 열람하고 새 보고서 링크를 DM으로 받습니다."}</p>${configured ? '<a class="button" href="/reports/auth/discord">Discord로 로그인하고 구독 신청 →</a><p class="hint">로그인 완료 안내를 DM으로 보내드립니다. 로그인은 이 브라우저에서 30일간 유지되며, 구독과 보고서 알림은 언제든 해제할 수 있습니다.</p>' : '<p class="notice">Discord 로그인 연결을 준비 중입니다.</p>'}</div>`);
  return page("보고서 관리 로그인", `${heading}<div class="panel narrow"><h2>${type === "admin" ? "관리자 로그인" : "업로드 전용 로그인"}</h2>${configured ? `<form action="/reports/login/${type}" method="post">${type === "admin" ? '<label>아이디<input name="username" required autocomplete="username"></label>' : ""}<label>${type === "admin" ? "비밀번호" : "업로드 키"}<input type="password" name="password" required autocomplete="current-password"></label><button class="button">로그인</button></form>` : '<p class="notice">운영자 설정이 필요합니다.</p>'}</div>`);
}
export function archive(reports, role, search, currentPage) {
  const all = reports.filter((r) => `${r.date} ${r.title} ${r.summary}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.date.localeCompare(a.date));
  const count = Math.max(1, Math.ceil(all.length / 30));
  const number = Math.min(Math.max(1, currentPage), count);
  const visible = all.slice((number - 1) * 30, number * 30);
  const pageUrl = (n) => `/reports?${new URLSearchParams({ q: search, page: String(n) })}`;
  return page("보고서 보관함", `${hero('DAILY <span>ARCHIVE.</span>', "오늘의 기회부터 지난 기록까지. 공모전·시장 정보·채용을 날짜별로 확인하세요.")}<form method="get" action="/reports" class="panel"><label>보고서 검색<input type="search" name="q" value="${esc(search)}" placeholder="날짜, 제목 또는 요약" maxlength="100"></label><button class="button secondary small">검색</button></form><div class="section-heading"><h2>누적 보고서 ${all.length}개</h2><small>LATEST FIRST / ${number} OF ${count}</small></div>${visible.map((r) => `<a class="archive-row" href="/reports/${r.date}"><div><span class="meta">${r.date}</span><h2>${esc(r.title)}</h2><p>${esc(r.summary)}</p></div><span class="tag accent">HTML 보고서 열기 ↗</span></a>`).join("") || '<p class="empty">등록된 보고서가 없습니다.</p>'}<div class="row">${number > 1 ? `<a class="button secondary" href="${esc(pageUrl(number - 1))}">이전 목록</a>` : ""}${number < count ? `<a class="button secondary" href="${esc(pageUrl(number + 1))}">다음 목록</a>` : ""}</div>`, role);
}
function readingPage(title, content, role) {
  return page(title, content, role).replace("</head>", '<style>' + readerShellStyles + '</style></head>').replace("<body>", '<body class="report-reader">');
}
export function viewer(report, role, opportunities = {}, focused = "", filter = "") {
  return readingPage(report.title, reportOverview(report, role, opportunities, focused, filter), role);
}
export function progressPage(opportunities, role, filter = "") {
  return readingPage("진행 현황", progressOverview(opportunities, role, filter), role);
}
export function publisherGuide({ instructions, design, context, research, today }, role) {
  const source = (id, title, text) => `<section class="panel guide-section" id="${id}"><h2>${title}</h2><pre>${esc(text)}</pre></section>`;
  const publishedToday = research.previousReports.some((report) => report.date === today);
  const content = `<div class="publisher-guide"><header class="panel"><h1>조사 자료</h1>
    <p>작업 지침, 조사 대상 정보, 디자인 기준과 현재 진행 기록을 이 페이지에서 읽을 수 있습니다.</p>
    <p>한국시간 <strong>${esc(today)}</strong> · <strong>stateVersion: ${research.stateVersion}</strong> · 오늘 보고서 <strong>${publishedToday ? "등록됨 · 중복 발행하지 마세요" : "미등록"}</strong></p>
    <p class="hint">진행 기록은 이 페이지를 열었을 때의 값입니다. 발행 직전에 새로고침하고 변경된 상태와 메모를 반영하세요.</p>
    <div class="row"><a class="button secondary small" href="/reports/upload?guide=1">최신 자료 새로고침</a><a class="button small" href="/reports/upload">HTML 업로드로 돌아가기</a></div>
    <nav class="row" aria-label="조사 자료 목차"><a href="#research-state">이전 보고·진행 기록</a><a href="#instructions">dots 운영 지침</a><a href="#context">조사 대상 정보</a><a href="#design">Design.md</a></nav></header>
    <section class="panel guide-section" id="research-state"><h2>이전 보고·진행 기록</h2><p>stateVersion, 기존 항목의 ID·상태·메모와 이전 보고서 목록이 포함된 전체 JSON입니다.</p><pre id="research-state-json">${esc(JSON.stringify(research, null, 2))}</pre></section>
    ${source("instructions", "dots 운영 지침", instructions)}${source("context", "조사 대상 정보", context)}${source("design", "Design.md", design)}</div>`;
  return readingPage("조사 자료", content, role).replace("</head>", `<style>.publisher-guide{min-width:0}.publisher-guide .guide-section{scroll-margin-top:24px;min-width:0}.publisher-guide pre{white-space:pre-wrap;overflow-wrap:anywhere;word-break:normal;font:inherit;line-height:1.8;margin:0;max-width:100%}.publisher-guide h1{font-size:clamp(26px,5vw,38px)}.publisher-guide nav{margin-top:24px;gap:18px}.publisher-guide nav a{text-decoration:underline}</style></head>`);
}
export function upload(today, role, published, deliveries, enabled, channelId = "") {
  const target = channelId ? "채널" : "DM";
  const pending = deliveries.filter((d) => d.date === today && d.status === "pending" && (channelId ? d.channelId === channelId : !d.channelId)).length;
  return page("HTML 업로드", `${hero('UPLOAD <span>BRIEF.</span>', "완성한 HTML을 올리면 개별 주소와 누적 목록이 함께 생성됩니다.")}<div class="panel">${published ? `<p class="notice">${esc(published.date)} 보고서를 등록했습니다. 주소: <a href="/reports/${published.date}">/reports/${published.date}</a> · <a href="/reports">전체 목록</a></p>` : ""}<form action="/reports/upload/preview" method="post" enctype="multipart/form-data"><label>발행일<input type="date" name="date" required value="${today}" max="${today}"></label><label>보고서 제목<input name="title" required maxlength="150" placeholder="겜마루 일일 지원 정보"></label><label>목록과 ${target}에 표시할 요약<input name="summary" maxlength="500" placeholder="핵심 기회와 추천 행동을 2~3문장으로 적어 주세요"></label><p class="hint">${target} 알림에는 제목과 이 요약을 함께 보냅니다. 요약이 길면 300자까지 표시합니다.</p><label>HTML 파일<input name="html" type="file" accept=".html,.htm,text/html" required></label><p class="hint">UTF-8 HTML, 최대 2MB. Design.md 스타일을 포함한 파일을 올려 주세요. 기존 날짜는 덮어쓰지 않습니다.</p><label><input name="notify" type="checkbox" value="yes" checked>${channelId ? "오늘 보고서의 제목·요약·링크를 Discord 서버 채널에 게시하기" : "오늘 보고서라면 승인·알림 동의한 구독자에게 요약·링크 DM 보내기"}</label><button class="button">HTML 미리보기</button></form></div><div class="panel"><h2>알림 처리</h2><p>오늘 대기 ${pending}건 · ${target} ${enabled ? "활성" : "꺼짐"}</p>${formButton("/reports/notify", channelId ? "오늘 보고서 채널 게시·대기 처리" : "남은 알림 처리", "", "secondary")}<p class="hint">${channelId ? "설정된 서버 채널에 하루 한 번 게시합니다. 채널을 볼 수 있는 멤버는 요약을 읽을 수 있고, 전체 보고서는 사이트의 구독 승인이 필요합니다. " : ""}전송 결과가 불확실한 메시지는 중복 발송하지 않습니다. 과거 보고서는 업로드해도 알림을 보내지 않습니다.</p></div><div class="row"><a class="button secondary small" href="/reports/upload?guide=1#context">조사 대상 정보</a><a class="button secondary small" href="/reports/upload?guide=1#design">Design.md</a><a class="button secondary small" href="/reports/upload?guide=1#research-state">이전 보고·진행 기록</a><a class="button secondary small" href="/reports/upload?guide=1#instructions">dots 운영 지침</a></div>`, role);
}
export function preview(draft, role) {
  const manifestNotice = draft.manifest ? `<p>진행 관리에 연결할 항목 ${draft.manifest.opportunities.length}개 · 조사 기준 버전 ${draft.manifest.stateVersion}</p><ul>${draft.manifest.opportunities.map((item) => `<li>${esc(item.title)} · ${esc(item.id)}</li>`).join("")}</ul>` : '<p class="notice">진행 항목 데이터가 없는 HTML입니다. 본문은 발행되지만 상태·메모 관리에는 연결되지 않습니다.</p>';
  const controls = `<section class="panel"><p class="notice">아직 발행하지 않았습니다. 아래 HTML의 내용과 원문 링크를 검토해 주세요. 미리보기는 30분간 유효합니다.</p>${manifestNotice}<form method="post" action="/reports/upload/publish">${hidden("draft", draft.id)}<label><input type="checkbox" name="confirmed" value="yes" required>내용을 확인했고 보고서 등록에 동의합니다.</label><button class="button">이 HTML 등록하기</button></form></section>`;
  const frame = `<iframe title="업로드한 HTML 미리보기" src="/reports/upload/preview/${draft.id}/html?reading=1" sandbox="allow-popups allow-popups-to-escape-sandbox" referrerpolicy="no-referrer" style="display:block;width:100%;height:65vh;border:1px solid var(--line)"></iframe>`;
  return page("HTML 미리보기", hero('PREVIEW <span>BRIEF.</span>', draft.title, draft.date) + controls + frame, role);
}

const statuses = { new: "신청 전", pending: "승인 대기", approved: "승인됨", revoked: "구독 해제", rejected: "반려" };
function noticeStatus(notice) {
  if (!notice) return "아직 보내지 않았습니다.";
  if (["pending", "sending"].includes(notice.status)) return notice.createdAt < Date.now() - 60000 ? "전송 결과를 확인하지 못했습니다." : "전송 중입니다. 잠시 후 전송 상태를 새로고침해 주세요.";
  return ({ sent: "전송했습니다. Discord DM을 확인해 주세요.", blocked: "Discord가 DM 전송을 거절했습니다. 봇이 같은 서버에 있는지와 서버의 DM 허용 설정을 확인해 주세요.", failed: "전송하지 못했습니다. 잠시 후 다시 요청해 주세요.", uncertain: "전송 결과를 확인하지 못했습니다. 받은 DM을 먼저 확인해 주세요.", unavailable: "봇 연결 설정이 필요합니다. 운영자에게 문의해 주세요.", cancelled: "구독 상태가 변경되어 전송을 취소했습니다." })[notice.status] || "전송 결과를 확인하지 못했습니다.";
}
function memberNotifications(member, applicationId) {
  const notice = member.approval_notice || member.login_notice;
  const invite = /^\d{17,20}$/.test(applicationId || "") ? `https://discord.com/oauth2/authorize?${new URLSearchParams({ client_id: applicationId, scope: "bot", permissions: "0" })}` : "";
  return `<section class="panel" aria-label="Discord 알림"><h2>Discord 확인 DM</h2><p role="status">${member.approval_notice ? "구독 승인 안내: " : member.login_notice ? "로그인 안내: " : ""}${esc(noticeStatus(notice))}</p>${notice?.status === "blocked" && invite ? `<p class="hint">사이트 로그인만으로 봇이 서버에 추가되지는 않습니다. 서버 관리자는 아래 링크로 봇을 추가할 수 있습니다.</p><p><a class="button secondary small" href="${esc(invite)}" target="_blank" rel="noopener noreferrer">봇을 서버에 추가 ↗</a></p>` : ""}<div class="row">${member.status === "approved" ? formButton("/reports/account/confirmation", "확인 DM 다시 받기", "", "secondary small") : ""}<a class="button secondary small" href="/reports/account">전송 상태 새로고침</a></div><p class="hint">승인 완료 시 확인 DM을 보냅니다. 수신 설정을 바꾼 뒤에는 재로그인 없이 다시 받을 수 있습니다.</p></section>`;
}
export function account(member, welcome = false, saved = false, applicationId = "", confirmation = false, channelMode = false) {
  const request = ["new", "rejected", "revoked"].includes(member.status);
  const approved = member.status === "approved";
  const explanation = approved ? "구독이 승인되었습니다. 일일 보고서와 지난 보고서를 열람할 수 있습니다." : member.status === "pending" ? "구독 신청이 접수되었습니다. 관리자가 승인하면 보고서를 열람할 수 있습니다." : member.status === "rejected" ? "구독 신청이 반려되었습니다. 이름을 확인하고 다시 신청할 수 있습니다." : member.status === "revoked" ? "현재 구독이 해제되어 있습니다. 다시 구독하려면 승인을 요청해 주세요." : "이름을 확인하고 구독 승인을 요청해 주세요.";
  return page("내 구독", `${hero('YOUR <span>BRIEF.</span>', `${member.name || member.display_name}님, 로그인되어 있습니다.`)}${welcome ? '<p class="notice" role="status">Discord 로그인이 완료되었습니다. 아래에서 구독 상태와 보고서를 확인하세요.</p>' : ""}${saved ? '<p class="notice" role="status">구독 설정을 저장했습니다.</p>' : ""}${confirmation ? '<p class="notice" role="status">확인 DM을 요청했습니다. 잠시 후 전송 상태를 새로고침해 주세요.</p>' : ""}<div class="panel narrow">${profile(member)}<p class="tag accent">${esc(statuses[member.status])}</p><p>${explanation}</p><div class="row">${approved ? '<a class="button" href="/reports">보고서 목록 열기 →</a>' : '<a class="button secondary" href="/reports/account">승인 상태 새로고침</a>'}<a class="button secondary" href="/">겜마루 홈</a></div>${memberNotifications(member, applicationId)}<form action="/reports/subscription" method="post"><label>신청자 이름<input name="name" required minlength="1" maxlength="60" value="${esc(member.name || member.display_name)}" autocomplete="name"></label>${channelMode ? '<p class="hint">일일 보고서의 제목·요약·링크는 Discord 서버 채널에 게시됩니다. 채널 알림은 Discord에서 설정해 주세요.</p>' : `<label><input type="checkbox" name="dm" value="yes" ${member.dm_opt_in ? "checked" : ""}>새 보고서 링크를 Discord DM으로 받겠습니다.</label>`}<button class="button">${request ? "구독 승인 요청" : "구독 설정 저장"}</button></form>${["pending", "approved"].includes(member.status) ? formButton("/reports/unsubscribe", member.status === "pending" ? "구독 신청 취소" : "구독 해제", "", "danger") : ""}<p class="hint">로그인은 이 브라우저에서 30일간 유지됩니다. DM 전송 여부와 관계없이 사이트를 이용할 수 있습니다.</p></div>`, "member");
}
export function admin(members, deliveries, channelMode = false) {
  const cards = members.filter((m) => m.status !== "new").map((m) => `<section class="card">${profile(m)}<p class="tag">${esc(statuses[m.status])}</p>${channelMode ? '<p class="hint">일일 보고서: 서버 채널 게시</p>' : `<p class="hint">보고서 DM ${m.dm_opt_in ? "동의" : "미동의"}</p>`}<p>승인 확인 DM: ${esc(noticeStatus(m.approval_notice))}</p>${m.approval_notice?.errorCode ? `<p class="hint">Discord 오류 코드: ${esc(m.approval_notice.errorCode)}</p>` : ""}<a href="https://discord.com/users/${m.id}" target="_blank" rel="noopener noreferrer">Discord 프로필 ↗</a><div class="row">${m.status === "pending" ? formButton(`/reports/admin/${m.id}/approve`, "구독 승인", "", "small") + formButton(`/reports/admin/${m.id}/reject`, "반려") : ""}${m.status === "approved" ? formButton(`/reports/admin/${m.id}/notify`, "승인 확인 DM 보내기") + formButton(`/reports/admin/${m.id}/revoke`, "승인 취소") : ""}</div></section>`).join("");
  return page("구독 승인", `${hero('CONTROL <span>ROOM.</span>', "보고서 구독을 승인하고 링크 알림 상태를 확인합니다.")}<div class="grid">${cards || '<p class="empty">구독 신청이 아직 없습니다.</p>'}</div><div class="section-heading"><h2>알림 기록</h2></div><div class="table-wrap"><table><thead><tr><th>날짜</th><th>전송 대상</th><th>상태</th></tr></thead><tbody>${deliveries.slice(-100).reverse().map((d) => `<tr><td>${esc(d.date)}</td><td>${esc(d.channelId ? `Discord 채널 ${d.channelId}` : members.find((m) => m.id === d.memberId)?.name || "")}</td><td>${esc(d.status)}</td></tr>`).join("")}</tbody></table></div><p class="hint">pending: 대기, sent: 전송됨, blocked: 전송 권한 없음, failed: 실패, uncertain: 수신 여부 불명, cancelled: 취소. uncertain은 자동 재발송하지 않습니다.</p>`, "admin");
}
