import { layout, hero, esc, hidden, profile, formButton } from "../portal/views.mjs";
export function page(title, content, role = "guest") {
  const nav = role === "admin" ? '<a href="/reports">보고서 목록</a><a href="/reports/upload">HTML 업로드</a><a href="/reports/admin">구독 승인</a>' : role === "publisher" ? '<a href="/reports/upload">HTML 업로드</a>' : '<a href="/reports">보고서 목록</a><a href="/reports/account">구독 설정</a>';
  return layout(title, content, role, nav).replace('action="/members/logout"', 'action="/reports/logout"');
}
export function login(type, configured) {
  const heading = hero('DAILY <span>ARCHIVE.</span>', "겜마루의 외부 후원·운영자금·유용한 정보를 모아 둔 보고서 보관함입니다.");
  if (type === "member") return page("보고서 로그인", `${heading}<div class="panel narrow"><h2>구독자 전용 보고서</h2><p>Discord 로그인 후 승인된 구독자만 열람할 수 있습니다.</p>${configured ? '<a class="button" href="/reports/auth/discord">Discord로 로그인 ↗</a>' : '<p class="notice">Discord 로그인 연결을 준비 중입니다.</p>'}</div>`);
  return page("보고서 관리 로그인", `${heading}<div class="panel narrow"><h2>${type === "admin" ? "관리자 로그인" : "업로드 전용 로그인"}</h2>${configured ? `<form action="/reports/login/${type}" method="post">${type === "admin" ? '<label>아이디<input name="username" required autocomplete="username"></label>' : ""}<label>${type === "admin" ? "비밀번호" : "업로드 키"}<input type="password" name="password" required autocomplete="current-password"></label><button class="button">로그인</button></form>` : '<p class="notice">운영자 설정이 필요합니다.</p>'}</div>`);
}
export function archive(reports, role, search, currentPage) {
  const all = reports.filter((r) => `${r.date} ${r.title} ${r.summary}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.date.localeCompare(a.date));
  const count = Math.max(1, Math.ceil(all.length / 30));
  const number = Math.min(Math.max(1, currentPage), count);
  const visible = all.slice((number - 1) * 30, number * 30);
  const pageUrl = (n) => `/reports?${new URLSearchParams({ q: search, page: String(n) })}`;
  return page("보고서 보관함", `${hero('DAILY <span>ARCHIVE.</span>', "오늘의 기회부터 지난 기록까지. 겜마루에 도착한 정보를 한곳에서 확인하세요.")}<form method="get" action="/reports" class="panel"><label>보고서 검색<input type="search" name="q" value="${esc(search)}" placeholder="날짜, 제목 또는 요약" maxlength="100"></label><button class="button secondary small">검색</button></form><div class="section-heading"><h2>누적 보고서 ${all.length}개</h2><small>LATEST FIRST / ${number} OF ${count}</small></div>${visible.map((r) => `<a class="archive-row" href="/reports/${r.date}"><div><span class="meta">${r.date}</span><h2>${esc(r.title)}</h2><p>${esc(r.summary)}</p></div><span class="tag accent">HTML 보고서 열기 ↗</span></a>`).join("") || '<p class="empty">등록된 보고서가 없습니다.</p>'}<div class="row">${number > 1 ? `<a class="button secondary" href="${esc(pageUrl(number - 1))}">이전 목록</a>` : ""}${number < count ? `<a class="button secondary" href="${esc(pageUrl(number + 1))}">다음 목록</a>` : ""}</div>`, role);
}
export function viewer(report, role) {
  return page(report.title, `${hero('DAILY <span>BRIEF.</span>', report.title, report.date)}<div class="row"><a class="button secondary" href="/reports">← 전체 보고서 목록</a><a class="button secondary" href="/reports/${report.date}/html" target="_blank" rel="noopener noreferrer">HTML만 새 탭에서 열기 ↗</a></div><p class="hint">${esc(report.summary)}</p><iframe title="${esc(report.title)}" src="/reports/${report.date}/html" sandbox="allow-popups allow-popups-to-escape-sandbox" referrerpolicy="no-referrer" style="width:100%;height:80vh;min-height:600px;border:1px solid var(--line);background:var(--navy)"></iframe>`, role);
}
export function upload(today, role, published, deliveries, enabled) {
  const pending = deliveries.filter((d) => d.date === today && d.status === "pending").length;
  return page("HTML 업로드", `${hero('UPLOAD <span>BRIEF.</span>', "완성한 HTML을 올리면 개별 주소와 누적 목록이 함께 생성됩니다.")}<div class="panel">${published ? `<p class="notice">${esc(published.date)} 보고서를 등록했습니다. 주소: <a href="/reports/${published.date}">/reports/${published.date}</a> · <a href="/reports">전체 목록</a></p>` : ""}<form action="/reports/upload/preview" method="post" enctype="multipart/form-data"><label>발행일<input type="date" name="date" required value="${today}" max="${today}"></label><label>보고서 제목<input name="title" required maxlength="150" placeholder="겜마루 일일 지원 정보"></label><label>목록에 표시할 요약<input name="summary" maxlength="500" placeholder="오늘 확인한 핵심 내용을 짧게 입력하세요"></label><label>HTML 파일<input name="html" type="file" accept=".html,.htm,text/html" required></label><p class="hint">UTF-8 HTML, 최대 2MB. Design.md 스타일을 포함한 파일을 올려 주세요. 기존 날짜는 덮어쓰지 않습니다.</p><label><input name="notify" type="checkbox" value="yes" checked>오늘 보고서라면 승인·알림 동의한 구독자에게 링크 DM 보내기</label><button class="button">HTML 미리보기</button></form></div><div class="panel"><h2>알림 처리</h2><p>오늘 대기 ${pending}건 · DM ${enabled ? "활성" : "꺼짐"}</p>${formButton("/reports/notify", "남은 알림 처리", "", "secondary")}<p class="hint">전송 결과가 불확실한 메시지는 중복 발송하지 않습니다. 과거 보고서는 업로드해도 알림을 보내지 않습니다.</p></div><div class="row"><a class="button secondary small" href="/reports/context">동아리 정보</a><a class="button secondary small" href="/reports/design">Design.md</a></div>`, role);
}
export function preview(draft, role) {
  const controls = `<section class="panel"><p class="notice">아직 발행하지 않았습니다. 아래 HTML의 내용과 원문 링크를 검토해 주세요. 미리보기는 30분간 유효합니다.</p><form method="post" action="/reports/upload/publish">${hidden("draft", draft.id)}<label><input type="checkbox" name="confirmed" value="yes" required>내용을 확인했고 보고서 등록에 동의합니다.</label><button class="button">이 HTML 등록하기</button></form></section>`;
  const frame = `<iframe title="업로드한 HTML 미리보기" src="/reports/upload/preview/${draft.id}/html" sandbox="allow-popups allow-popups-to-escape-sandbox" referrerpolicy="no-referrer" style="display:block;width:100%;height:65vh;border:1px solid var(--line)"></iframe>`;
  return page("HTML 미리보기", hero('PREVIEW <span>BRIEF.</span>', draft.title, draft.date) + controls + frame, role);
}

const statuses = { new: "신청 전", pending: "승인 대기", approved: "승인됨", revoked: "구독 해제", rejected: "반려" };
export function account(member) {
  const request = ["new", "rejected", "revoked"].includes(member.status);
  return page("구독 설정", `${hero('YOUR <span>BRIEF.</span>', "이름과 Discord 프로필로 구독 승인을 요청하세요.")}<div class="panel narrow">${profile(member)}<p class="tag accent">${esc(statuses[member.status])}</p>${member.status === "approved" ? '<p><a class="button" href="/reports">보고서 목록 열기</a></p>' : ""}<form action="/reports/subscription" method="post">${request ? `<label>신청자 이름<input name="name" required minlength="2" maxlength="60" value="${esc(member.name)}"></label>` : ""}<label><input type="checkbox" name="dm" value="yes" ${member.dm_opt_in ? "checked" : ""}>새 보고서 링크를 Discord DM으로 받겠습니다.</label><button class="button">${request ? "구독 승인 요청" : "알림 설정 저장"}</button></form>${formButton("/reports/unsubscribe", "구독 해제", "", "danger")}<p class="hint">DM 수신에는 봇과의 공통 Discord 서버 및 DM 허용 설정이 필요합니다.</p></div>`, "member");
}
export function admin(members, deliveries) {
  return page("구독 승인", `${hero('CONTROL <span>ROOM.</span>', "보고서 구독을 승인하고 링크 알림 상태를 확인합니다.")}<div class="grid">${members.filter((m) => m.status !== "new").map((m) => `<section class="card">${profile(m)}<p class="tag">${esc(statuses[m.status])}</p><p class="hint">DM ${m.dm_opt_in ? "동의" : "미동의"}</p><a href="https://discord.com/users/${m.id}" target="_blank" rel="noopener noreferrer">Discord 프로필 ↗</a><div class="row">${m.status === "pending" ? formButton(`/reports/admin/${m.id}/approve`, "구독 승인", "", "small") + formButton(`/reports/admin/${m.id}/reject`, "반려") : ""}${m.status === "approved" ? formButton(`/reports/admin/${m.id}/revoke`, "승인 취소") : ""}</div></section>`).join("") || '<p class="empty">구독 신청이 아직 없습니다.</p>'}</div><div class="section-heading"><h2>알림 기록</h2></div><div class="table-wrap"><table><thead><tr><th>날짜</th><th>회원</th><th>상태</th></tr></thead><tbody>${deliveries.slice(-100).reverse().map((d) => `<tr><td>${esc(d.date)}</td><td>${esc(members.find((m) => m.id === d.memberId)?.name || "")}</td><td>${esc(d.status)}</td></tr>`).join("")}</tbody></table></div><p class="hint">pending: 대기, sent: 전송됨, blocked: DM 차단, failed: 실패, uncertain: 수신 여부 불명, cancelled: 취소. uncertain은 자동 재발송하지 않습니다.</p>`, "admin");
}
