import assert from "node:assert/strict";
import { chromium } from "playwright";
import { mkdtemp, mkdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { randomBytes } from "node:crypto";
import { once } from "node:events";
import { configuration, seoulClock } from "../config.mjs";
import { Store } from "../store.mjs";
import { validateReport } from "../schema.mjs";
import { createFundingServer } from "../server.mjs";
import { exampleReport } from "./fixtures.mjs";

const directory = await mkdtemp(path.join(tmpdir(), "gammaru-browser-"));
const output = path.resolve("test-results/funding");
await mkdir(output, { recursive: true });
const config = configuration({ FUNDING_ADMIN_TOKEN: randomBytes(32).toString("hex"), FUNDING_DATA_DIR: directory, FUNDING_PORT: "0" });
const store = new Store(directory);
const { date } = seoulClock();
store.startRun(date);
store.saveReport({ ...validateReport(exampleReport, date), date, generatedAt: new Date().toISOString(), provider: "codex" }, "");
const app = createFundingServer(config, { store });
app.server.listen(0, "127.0.0.1"); await once(app.server, "listening");
config.origin = `http://127.0.0.1:${app.server.address().port}`;
const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL || "msedge", headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
  const errors = []; page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(config.origin);
  await page.locator("#login").waitFor({ state: "visible" });
  await page.locator("#password").fill(config.token);
  await page.locator("#login-form button").click();
  await page.locator("#dashboard").waitFor({ state: "visible" });
  assert.equal(await page.locator("#opportunities .card").count(), 2);
  await page.screenshot({ path: path.join(output, "desktop.png"), fullPage: true });
  await page.locator('[data-tab="actions"]').click();
  const approve = page.locator('[data-action="approve"]');
  assert.equal(await approve.isDisabled(), true);
  await page.locator('[name="body"]').fill("# 수정한 제안서\n\n운영자가 확인한 내용입니다.");
  await page.locator('[name="confirm"]').check();
  assert.equal(await approve.isDisabled(), true, "Unsaved edits must not be approved");
  await page.locator('[data-action="save"]').click();
  await page.waitForFunction(() => document.querySelector('[name="confirm"]')?.checked === false);
  await page.locator('[name="confirm"]').check();
  await approve.click();
  await page.locator(".download").waitFor({ state: "visible" });
  assert.equal(store.state().actions[0].result.document, "# 수정한 제안서\n\n운영자가 확인한 내용입니다.");
  await page.screenshot({ path: path.join(output, "approved-document.png"), fullPage: true });
  await page.locator('[data-tab="report"]').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(output, "mobile.png"), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, "Mobile page must not overflow horizontally");
  await page.locator('[data-tab="history"]').click();
  await page.locator("#history-panel").waitFor({ state: "visible" });
  await page.locator("#logout").click();
  await page.locator("#login").waitFor({ state: "visible" });
  assert.equal((await page.request.get(`${config.origin}/api/state`)).status(), 401);
  assert.deepEqual(errors, []);
  console.log("Browser passed: login, private reports, draft edits, approval, document creation, mobile layout, history, logout.");
} finally {
  await browser.close();
  await new Promise((resolve) => app.server.close(resolve));
  store.close();
  await rm(directory, { recursive: true, force: true });
}
