import { readFileSync } from "node:fs";
import path from "node:path";
import { digest } from "../schema.mjs";

const css = readFileSync(path.join(process.cwd(), "funding/portal/style.css"), "utf8");
export const designHash = digest(readFileSync(path.join(process.cwd(), "Design.md"), "utf8"));
export const esc = (value = "") => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
export const kinds = { cash: "운영자금", in_kind: "현물·도구", prize: "상금", sponsorship: "후원", information: "유용한 정보" };
const eligibility = { likely: "지원 검토 가능", uncertain: "자격 확인 필요", ineligible: "현재 자격 미충족" };
const status = { new: "신청 전", pending: "승인 대기", approved: "승인됨", rejected: "반려", revoked: "구독 해제" };
export const hidden = (name, value) => `<input type="hidden" name="${esc(name)}" value="${esc(value)}">`;
export const formButton = (action, label, extra = "", cls = "secondary small") => `<form method="post" action="${esc(action)}">${extra}<button class="button ${cls}">${esc(label)}</button></form>`;
export function layout(title, content, role = "member", navigation) {
  const nav = navigation ?? (role === "admin" ? '<a href="/admin">구독 관리</a><a href="/admin/actions">실행 승인</a><a href="/members/reports">보고서</a>' : role === "publisher" ? '<a href="/publisher">보고서 등록</a>' : '<a href="/members/reports">보고서</a><a href="/members">구독 설정</a>');
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="color-scheme" content="dark"><title>${esc(title)} — GAMMARU</title><link rel="icon" href="/brand/gammaru-mark.png"><style>${css}</style></head><body><a class="skip" href="#content">본문 바로가기</a><header class="topbar"><a class="brand" href="/" aria-label="겜마루 홈"><img src="/brand/gammaru-mark.png" alt="" width="38" height="30">GAMMARU</a><span class="member-label">MEMBERS ONLY</span><nav aria-label="회원 메뉴">${nav}${role !== "guest" ? formButton("/members/logout", "로그아웃", "", "text-button") : ""}</nav></header><main id="content">${content}</main><footer><span>GAMMARU · SOONGSIL UNIVERSITY</span><span>BUILD TOGETHER. GO FURTHER.</span></footer></body></html>`;
}
export function hero(title, summary, date = "") {
  return `<section class="hero"><div><div class="eyebrow">GAMMARU / DAILY OPPORTUNITIES</div><h1>${title}</h1><p class="lead">${esc(summary)}</p></div>${date ? `<div class="edition"><small>DAILY EDITION / KST</small><strong>${esc(date)}</strong><small>외부 후원 · 운영자금 · 유용한 정보</small></div>` : ""}</section>`;
}
const list = (items) => `<ul>${items.map((s) => `<li>${esc(s)}</li>`).join("")}</ul>`;
export function reportContent(report) {
  const counts = [report.opportunities.filter((o) => ["cash", "sponsorship"].includes(o.kind)).length, report.opportunities.filter((o) => o.kind === "in_kind").length, report.opportunities.filter((o) => o.kind === "prize").length, report.opportunities.filter((o) => o.kind === "information").length];
  return `${hero('DAILY <span>BRIEF.</span>', report.summary, report.date)}<section class="stats" aria-label="유형별 정보 수">${["운영자금·후원", "현물·도구", "수상 조건부 상금", "유용한 정보"].map((label, i) => `<div class="stat"><strong>${String(counts[i]).padStart(2, "0")}</strong><span>${label}</span></div>`).join("")}</section><div class="section-heading"><h2>겜마루의 다음 기회</h2><small>OPPORTUNITIES / ${report.opportunities.length}</small></div><div class="grid">${report.opportunities.map((o, i) => `<article class="card"><div class="tags"><span class="tag accent">${esc(kinds[o.kind])}</span><span class="tag">${esc(eligibility[o.eligibility])}</span><span class="tag pink">${o.deadline ? `${esc(o.deadline)} 마감` : "마감일 미확인·상시 여부 확인"}</span></div><h2>${String(i + 1).padStart(2, "0")}. ${esc(o.title)}</h2><p class="organization">${esc(o.organization)}</p><p class="benefit">${esc(o.benefit)}</p><h3>겜마루와의 연결</h3><p>${esc(o.fitReason)}</p><h3>지원 자격과 준비</h3><p>${esc(o.eligibilityReason)}</p>${list(o.requirements)}<h3>추천하는 다음 행동</h3>${list(o.nextSteps)}<div class="sources">${o.sources.map((s) => `<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a><p>${esc(s.evidence)}</p>`).join("")}</div></article>`).join("") || '<div class="empty">오늘 확인된 지원 기회가 없습니다. 아래 조사 범위와 확인하지 못한 내용을 참고해 주세요.</div>'}</div><div class="section-heading"><h2>조사 노트</h2><small>RESEARCH NOTES</small></div>${report.warnings.length ? `<aside class="notice">${list(report.warnings)}</aside>` : ""}<div class="panel"><h3>오늘 확인한 범위</h3>${list(report.searched)}<p class="hint">지원 금액·자격·마감 시간은 원문을 최종 확인하세요. 추천 행동의 실제 제출·발송은 운영진의 별도 승인을 거칩니다.</p><p class="meta">SOURCE: ${esc(report.provider)} / CHECKED: ${esc(report.checkedAt || report.generatedAt)}<br>DESIGN: ${designHash.slice(0, 12)}</p></div>`;
}
export const renderReport = (report) => layout(`${report.date} 데일리 브리프`, reportContent(report));
export function loginPage(type, configured = true) {
  if (type === "member") return layout("구독자 로그인", `${hero('GO <span>FURTHER.</span>', "겜마루를 위한 후원, 운영자금, 그리고 다음 제작에 도움이 되는 정보를 매일 모읍니다.")}<section class="panel narrow"><h2>구독자 전용 데일리 브리프</h2><p>Discord로 로그인하고 구독을 신청하세요. 운영진 승인 후 보고서를 열람할 수 있습니다.</p>${configured ? '<a class="button" href="/members/auth/discord">Discord로 로그인 ↗</a>' : '<p class="notice">Discord 로그인 연결을 준비 중입니다.</p>'}<p class="hint">이름과 Discord 프로필은 구독 승인에 사용합니다. DM 알림은 별도로 선택할 수 있습니다.</p></section>`, "guest");
  const admin = type === "admin";
  return layout(admin ? "운영자 로그인" : "보고서 등록 로그인", `${hero(admin ? 'CONTROL <span>ROOM.</span>' : 'PUBLISH <span>BRIEF.</span>', admin ? "구독 요청과 실행 제안을 검토합니다." : "오늘 확인한 정보를 날짜별 보고서로 등록합니다.")}<section class="panel narrow"><h2>${admin ? "운영자 로그인" : "보고서 등록 전용 로그인"}</h2>${configured ? `<form method="post" action="/${admin ? "admin" : "publisher"}/login">${admin ? '<label>아이디<input name="username" autocomplete="username" required maxlength="100"></label>' : ""}<label>${admin ? "비밀번호" : "등록 키"}<input name="password" type="password" autocomplete="current-password" required maxlength="256"></label><button class="button">로그인</button></form>` : '<p class="notice">보고서 등록 계정이 아직 설정되지 않았습니다.</p>'}</section>`, "guest");
}
export function profile(member) {
  const avatar = member.avatar ? `https://cdn.discordapp.com/avatars/${member.id}/${member.avatar}.png?size=64` : "https://cdn.discordapp.com/embed/avatars/0.png";
  return `<div class="profile"><img class="avatar" src="${esc(avatar)}" alt=""><div><strong>${esc(member.name || member.display_name)}</strong><p class="hint">${esc(member.username)} · ${esc(member.id)}</p></div></div>`;
}
export function memberPage(member) {
  const canRequest = ["new", "revoked", "rejected"].includes(member.status);
  return layout("구독 설정", `${hero('YOUR <span>BRIEF.</span>', "새로운 기회는 매일, 알림은 원하는 방식으로.")}<section class="panel narrow">${profile(member)}<p class="tag accent">${esc(status[member.status])}</p>${member.status === "approved" ? '<p><a class="button" href="/members/reports">보고서 읽기 ↗</a></p>' : '<p>운영진이 이름과 Discord 프로필을 확인한 뒤 구독을 승인합니다.</p>'}<form method="post" action="/members/subscription">${canRequest ? `<label>신청자 이름<input name="name" value="${esc(member.name)}" required minlength="2" maxlength="60" autocomplete="name"></label><p class="hint">동아리에서 확인할 수 있는 이름을 입력해 주세요.</p>` : ""}<label><input type="checkbox" name="dm" value="yes" ${member.dm_opt_in ? "checked" : ""}>새 보고서 링크를 Discord DM으로 받겠습니다.</label><button class="button">${canRequest ? "구독 승인 요청" : "알림 설정 저장"}</button></form>${["pending", "approved"].includes(member.status) ? `<hr>${formButton("/members/unsubscribe", "구독 해제", "", "danger")}` : ""}<p class="hint">DM을 받으려면 봇과 같은 서버에 참여하고 Discord의 DM 허용 설정을 확인하세요. 구독 해제 즉시 열람 권한과 이후 알림이 중단됩니다.</p></section>`);
}
export function archivePage(editions, role, today) {
  return layout("데일리 브리프", `${hero('DAILY <span>BRIEF.</span>', "함께 만드는 게임에, 더 많은 가능성을. 겜마루의 외부 후원과 운영자금 소식을 모았습니다.", today)}${!editions.some((e) => e.date === today) ? '<p class="notice">오늘 보고서는 아직 도착하지 않았습니다. 아래 날짜는 이전 보고서의 발행일입니다.</p>' : ""}<section>${editions.map((e) => `<a class="archive-row" href="/members/reports/${e.date}"><div><strong>${e.date}</strong><p>${esc(e.summary)}</p></div><span class="tag accent">보고서 읽기 ↗</span></a>`).join("") || '<p class="empty">발행된 보고서가 아직 없습니다.</p>'}</section>`, role);
}
export function adminPage(members, deliveries, config, hasToday) {
  return layout("구독 승인", `${hero('CONTROL <span>ROOM.</span>', "이름과 Discord 프로필을 확인하고 구독 요청을 승인하세요.")}<div class="tabs"><a href="/admin" aria-current="page">구독 관리</a><a href="/admin/actions">실행 승인</a><a href="/publisher">보고서 등록</a><a href="/members/reports">뉴스레터</a></div><p class="notice">오늘 보고서: ${hasToday ? "발행됨" : "미도착"} · Discord DM: ${config.dmEnabled && config.discordBotToken ? "활성" : "정지"} · 팩트챗 자동 대체: ${config.fallbackEnabled ? "활성" : "정지"}</p><div class="grid">${members.map((m) => `<section class="card">${profile(m)}<p class="tag">${esc(status[m.status])}</p><p class="hint">DM ${m.dm_opt_in ? "동의" : "미동의"} · 신청 ${esc(m.requested_at || "없음")}</p><a class="hint" href="https://discord.com/users/${m.id}" target="_blank" rel="noopener noreferrer">Discord 프로필 ↗</a><div class="row">${m.status === "pending" ? formButton(`/admin/members/${m.id}/approve`, "구독 승인", "", "small") + formButton(`/admin/members/${m.id}/reject`, "반려") : ""}${m.status === "approved" ? formButton(`/admin/members/${m.id}/revoke`, "승인 취소", "", "danger small") : ""}</div></section>`).join("") || '<p class="empty">아직 구독 요청이 없습니다.</p>'}</div><div class="section-heading"><h2>최근 DM 전송 상태</h2><small>DELIVERY LOG</small></div><div class="table-wrap"><table><thead><tr><th>보고서</th><th>이름</th><th>상태</th></tr></thead><tbody>${deliveries.map((d) => `<tr><td>${esc(d.date)}</td><td>${esc(d.name)}</td><td>${esc(d.status)}</td></tr>`).join("")}</tbody></table></div><p class="hint">uncertain은 응답이 끊겨 수신 여부를 확인할 수 없는 상태입니다. 중복 알림을 막기 위해 자동 재발송하지 않습니다. failed·blocked는 발송 실패 또는 DM 차단입니다.</p>`, "admin");
}
export function publisherPage(date, existing, input = "") {
  return layout("보고서 등록", `${hero('PUBLISH <span>BRIEF.</span>', "공식 원문을 확인한 오늘의 후원·운영자금·유용한 정보를 등록합니다.", date)}<section class="panel"><p class="notice">${existing ? "오늘 보고서가 이미 발행되었습니다. 다른 내용으로 덮어쓰거나 중복 알림을 보내지 않습니다." : "검증과 미리보기를 거쳐 발행하면 승인된 구독자에게 알림이 예약됩니다."}</p><div class="row"><a class="button secondary small" href="/publisher/context">동아리 정보</a><a class="button secondary small" href="/publisher/design">Design.md</a><a class="button secondary small" href="/publisher/instructions">수집 지침·입력 형식</a></div><form method="post" action="/publisher/preview"><label>조사 결과 JSON<textarea class="code" name="report" required maxlength="250000" spellcheck="false">${esc(input)}</textarea></label><button class="button">검증하고 HTML 미리보기</button></form></section>`, "publisher");
}
export function previewPage(report, raw) {
  return layout("발행 미리보기", `<section class="notice"><p>미리보기입니다. 날짜·원문·자격·마감을 검토한 뒤 발행하세요.</p><form method="post" action="/publisher/publish">${hidden("report", raw)}<label><input type="checkbox" name="confirmed" value="yes" required>오늘 공식 원문을 확인했고, 구독자 대상 보고서 발행에 동의합니다.</label><button class="button">오늘 보고서 발행</button></form></section>${reportContent(report)}`, "publisher");
}
export function actionsPage(actions) {
  return layout("실행 승인", `${hero('NEXT <span>MOVE.</span>', "추천을 검토하고, 승인한 내용만 실행합니다.")}<div class="tabs"><a href="/admin">구독 관리</a><a href="/admin/actions" aria-current="page">실행 승인</a><a href="/members/reports">뉴스레터</a></div>${actions.map((a) => `<section class="panel"><p class="tag">${esc(a.status)} · ${esc(a.report_date)}</p><h2>${esc(a.payload.title)}</h2><p>${esc(a.payload.opportunityTitle)}</p><p class="hint">${a.payload.kind === "send_email" ? `이메일 발송 / 발신: ${esc(a.payload.from || "설정 필요")}` : "문서 작성"} · 마감 ${esc(a.deadline || "미확인")}</p>${a.payload.sources.map((s) => `<a class="button secondary small" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a>`).join(" ")}${["pending", "approved"].includes(a.status) ? `<form method="post" action="/admin/actions/${a.id}/save">${hidden("hash", a.hash)}<label>수신자<input name="recipient" value="${esc(a.payload.recipient)}" ${a.payload.kind === "prepare_brief" ? "readonly" : 'type="email" required'}></label><label>제목<input name="subject" maxlength="300" value="${esc(a.payload.subject)}"></label><label>본문<textarea name="body" required maxlength="12000">${esc(a.payload.body)}</textarea></label><button class="button secondary">초안 저장 · 기존 승인 취소</button><label><input name="confirmed" type="checkbox" value="yes">저장된 수신자·제목·본문과 원문을 확인했습니다.</label><button class="button" formaction="/admin/actions/${a.id}/approve">저장된 내용 승인 후 실행</button><p class="hint">수정한 내용은 먼저 저장해야 승인할 수 있습니다.</p></form>${formButton(`/admin/actions/${a.id}/reject`, "거절", "", "danger small")}` : `<details><summary>실행 내용</summary><pre>${esc(a.payload.body)}</pre></details>`}${a.result?.document ? `<a class="button secondary" href="/admin/actions/${a.id}/document">완성 문서 다운로드</a>` : ""}${a.status === "uncertain" ? `<p class="notice">메일 서비스에서 실제 발송 내역을 확인한 뒤 처리하세요. 자동 재발송하지 않습니다.</p><div class="row">${formButton(`/admin/actions/${a.id}/resolve`, "발송 확인", hidden("outcome", "completed"))}${formButton(`/admin/actions/${a.id}/resolve`, "종결 · 재발송 안 함", hidden("outcome", "rejected"))}</div>` : ""}</section>`).join("") || '<p class="empty">실행 승인을 기다리는 제안이 없습니다.</p>'}`, "admin");
}
